### ISSUE TITLE
K8s deployment and attached volumes

### ISSUE THREAD

**Issue by matnar** [delimitrou/DeathStarBench#28]
Considering the social network benchmark, there is an issue with the deployment of components: nginx-thrift and media-frontend. 

Both the deployments attach volumes which nonetheless are defined as local folders. When the benchmark is deployed in a distributed environment, those folders and files cannot be found. 

```
volumes:
      - name: lua-scripts
        hostPath: 
          path: /root/DeathStarBench/socialNetwork/nginx-web-server/lua-scripts-k8s
          type: Directory
```

This should be a remote folder.
